<?php

namespace LLMSpeak\Enums;

enum MediaResolutionEnum: string
{
    case MEDIA_RESOLUTION_UNSPECIFIED = 'MEDIA_RESOLUTION_UNSPECIFIED';
    case MEDIA_RESOLUTION_LOW = 'MEDIA_RESOLUTION_LOW';
    case MEDIA_RESOLUTION_MEDIUM = 'MEDIA_RESOLUTION_MEDIUM';
    case MEDIA_RESOLUTION_HIGH = 'MEDIA_RESOLUTION_HIGH';

}
